# Generated by Django 4.2.18 on 2025-02-12 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pharmacy_name",
                    models.CharField(max_length=255, verbose_name="약국명"),
                ),
                (
                    "prescription_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="처방전 번호"
                    ),
                ),
                ("prescription_date", models.DateField(verbose_name="처방일자")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="children.children",
                        verbose_name="아동",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방전",
                "verbose_name_plural": "처방전 목록",
                "db_table": "prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyEnvelope",
            fields=[
                ("envelope_id", models.AutoField(primary_key=True, serialize=False)),
                ("pharmacy_name", models.CharField(max_length=255)),
                ("prescription_number", models.CharField(max_length=50, unique=True)),
                ("prescription_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="children.children",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_envelopes",
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="약품명")),
                ("dosage", models.CharField(max_length=50, verbose_name="복용량")),
                ("quantity", models.IntegerField(verbose_name="수량")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="registerPrescription.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "처방약",
                "verbose_name_plural": "처방약 목록",
                "db_table": "medicines",
                "ordering": ["created_at"],
            },
        ),
    ]
