# Generated by Django 4.2.18 on 2025-02-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registerPrescription", "0002_alter_pharmacyenvelope_prescription_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(
                db_column="medicine_name", max_length=255, verbose_name="약품명"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="prescription",
            field=models.ForeignKey(
                db_column="envelope_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="registerPrescription.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacyenvelope",
            name="prescription_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
