# Generated by Django 4.2.18 on 2025-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registerPrescription",
            "0003_alter_medicine_name_alter_medicine_prescription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_number",
            field=models.CharField(max_length=50, verbose_name="처방전 번호"),
        ),
    ]
