# Generated by Django 4.2.18 on 2025-02-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registerPrescription", "0004_alter_prescription_prescription_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
