# Generated by Django 4.2.18 on 2025-02-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registerPrescription", "0005_alter_prescription_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="id",
            new_name="prescription_id",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="id",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="quantity",
        ),
        migrations.AddField(
            model_name="medicine",
            name="duration",
            field=models.IntegerField(default=0, verbose_name="투약일수"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicine",
            name="frequency",
            field=models.IntegerField(default=0, verbose_name="투약횟수"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="duration",
            field=models.CharField(blank=True, max_length=10, verbose_name="투약일수"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="pharmacy_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="약국주소"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="total_amount",
            field=models.CharField(blank=True, max_length=50, verbose_name="총액"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="prescription",
            field=models.ForeignKey(
                db_column="prescription_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="registerPrescription.prescription",
            ),
        ),
        migrations.DeleteModel(
            name="PharmacyEnvelope",
        ),
    ]
