# Generated by Django 4.2.18 on 2025-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchPharmacy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("map_info", models.TextField(blank=True)),
                ("etc", models.TextField(blank=True)),
                ("mon_start", models.CharField(blank=True, max_length=4)),
                ("mon_end", models.CharField(blank=True, max_length=4)),
                ("tue_start", models.CharField(blank=True, max_length=4)),
                ("tue_end", models.CharField(blank=True, max_length=4)),
                ("wed_start", models.CharField(blank=True, max_length=4)),
                ("wed_end", models.CharField(blank=True, max_length=4)),
                ("thu_start", models.CharField(blank=True, max_length=4)),
                ("thu_end", models.CharField(blank=True, max_length=4)),
                ("fri_start", models.CharField(blank=True, max_length=4)),
                ("fri_end", models.CharField(blank=True, max_length=4)),
                ("sat_start", models.CharField(blank=True, max_length=4)),
                ("sat_end", models.CharField(blank=True, max_length=4)),
                ("sun_start", models.CharField(blank=True, max_length=4)),
                ("sun_end", models.CharField(blank=True, max_length=4)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="searchPharm_latitud_3c5378_idx",
                    ),
                    models.Index(fields=["name"], name="searchPharm_name_bd61a3_idx"),
                ],
            },
        ),
    ]
