# Generated by Django 4.2.18 on 2025-02-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ykiho", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=1000)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("weekday_hours", models.JSONField(null=True)),
                ("saturday_hours", models.JSONField(null=True)),
                ("sunday_hours", models.JSONField(null=True)),
                ("reception_hours", models.JSONField(null=True)),
                ("lunch_time", models.JSONField(null=True)),
                ("holiday_closed", models.BooleanField(default=True)),
                ("holiday_info", models.JSONField(null=True)),
                ("sunday_closed", models.BooleanField(default=True)),
                ("hospital_type", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="searchHospi_latitud_b40ef9_idx",
                    ),
                    models.Index(
                        fields=["department"], name="searchHospi_departm_d16356_idx"
                    ),
                ],
            },
        ),
    ]
