# Generated by Django 4.2.18 on 2025-02-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyEnvelope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacy_name", models.CharField(max_length=255)),
                ("prescription_number", models.CharField(max_length=50, unique=True)),
                ("prescription_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_envelopes",
                        to="searchHospital.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ykiho", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=1000)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("weekday_hours", models.JSONField(null=True)),
                ("saturday_hours", models.JSONField(null=True)),
                ("sunday_hours", models.JSONField(null=True)),
                ("reception_hours", models.JSONField(null=True)),
                ("lunch_time", models.JSONField(null=True)),
                ("holiday_closed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="searchHospi_latitud_b40ef9_idx",
                    ),
                    models.Index(
                        fields=["department"], name="searchHospi_departm_d16356_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="searchHospital.user",
            ),
        ),
    ]
