# Generated by Django 4.2.18 on 2025-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="holiday_info",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="sunday_closed",
            field=models.BooleanField(default=True),
        ),
    ]
