# Generated by Django 4.2.18 on 2025-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0002_hospital_holiday_info_hospital_sunday_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
