# Generated by Django 4.2.18 on 2025-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0003_hospital_hospital_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
