# Generated by Django 4.2.18 on 2025-02-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0004_alter_hospital_hospital_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="hospital_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
