# Generated by Django 4.2.18 on 2025-02-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("searchHospital", "0005_alter_hospital_hospital_type"),
        ("searchHospital", "new_migration"),
    ]

    operations = []
